apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
      - name: kubernetes-app
        image: shrikantk7/kubernetes:1.0  # Use the Docker image name and tag
        ports:
        - containerPort: 8080
