apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app-service
spec:
  selector:
    app: kubernetes-app
  ports:
  - protocol: TCP
    port: 80  # Use any port you prefer
    targetPort: 8080
    nodePort: 30070
  type: NodePort